server:
  port: 22605

spring:
  application:
    name: cniface-platform
  jackson:
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    type: com.zaxxer.hikari.HikariDataSource

    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db/cniface
    username: admin
    password: cniface
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
      resolve-lazily: true
  h2:
    console:
      enabled: true


grpc:
  client:
    cniface:
      address: ${CNIFACE_GRPC_ADDR:static://127.0.0.1:22506}
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

jwt:
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  token-validity-in-seconds: 86400
  token-validity-in-seconds-for-remember-me: 108000