server:
  port: 22605

spring:
  application:
    name: cniface-platform
  jackson:
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db/cniface
    username: admin
    password: cniface
#  sql:
#    init:
#      data-locations: classpath:data.sql
#      mode: always
  jpa:
    hibernate:
#      ddl-auto: update
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
      resolve-lazily: true
  h2:
    console:
      enabled: true


grpc:
  client:
    cniface:
      address: ${CNIFACE_GRPC_ADDR:static://127.0.0.1:22506}
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

jwt:
  # This token must be encoded using Base64 with mininum 88 Bits (you can type `echo 'secret-key'|base64` on your command line)
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # token is valid 24 hours
  token-validity-in-seconds: 86400
  # valid 30 hours
  token-validity-in-seconds-for-remember-me: 108000
#  route:
#    authentication:
#      path: auth
#      refresh: refresh