server:
  port: 22605

spring:
  application:
    name: cniface-platform
  jackson:
#    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL

grpc:
  client:
    cniface:
      address: 'static://127.0.0.1:22506'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

